SELECT USER
FROM DUAL;

SELECT USER
FROM DUAL;
--==>> SCOTT

--○ 기존 테이블 삭제
DROP TABLE TBL_MEMBER;
--==>> Table TBL_MEMBER이(가) 삭제되었습니다.

--○ 테이블 생성
CREATE TABLE TBL_MEMBER
( SID   NUMBER
, NAME  VARCHAR2(30)     NOT NULL
, TEL   VARCHAR2(30) 
, CONSTRAINT MEMBER_SID_PK PRIMARY KEY(SID)
);
--==>>Table TBL_MEMBER이(가) 생성되었습니다.

--○ 기존 시퀀스 제거
DROP SEQUENCE MEMBERSEQ;

--○ 시퀀스 생성
CREATE SEQUENCE MEMBERSEQ
NOCACHE;

--○ 샘플 데이터 입력 
INSERT INTO TBL_MEMBER(SID, NAME, TEL) VALUES(MEMBERSEQ.NEXTVAL, '박나현', '010-1111-1111');
INSERT INTO TBL_MEMBER(SID, NAME, TEL) VALUES(MEMBERSEQ.NEXTVAL, '한혜림', '010-2222-2222');
INSERT INTO TBL_MEMBER(SID, NAME, TEL) VALUES(MEMBERSEQ.NEXTVAL, '김아별', '010-3333-3333');
INSERT INTO TBL_MEMBER(SID, NAME, TEL) VALUES(MEMBERSEQ.NEXTVAL, '선혜연', '010-4444-4444');
INSERT INTO TBL_MEMBER(SID, NAME, TEL) VALUES(MEMBERSEQ.NEXTVAL, '전혜림', '010-5555-5555');
--==>> 1 행 이(가) 삽입되었습니다.

--○ 확인
SELECT SID, NAME, TEL FROM TBL_MEMBER ORDER BY SID
;
--==>>
/*
1	박나현	010-1111-1111
2	한혜림	010-2222-2222
3	김아별	010-3333-3333
4	선혜연	010-4444-4444
5	전혜림	010-5555-5555
*/

--○ 커밋
COMMIT;
--==>> 커밋 완료.

--○ 인원 수 확인 
SELECT COUNT(*) AS COUNT
FROM TBL_MEMBER;
--> 한 줄 구성
SELECT COUNT(*) AS COUNT FROM TBL_MEMBER
;
--==>> 5

--○ 회원 정보 조회 
SELECT SID, NAME, TEL
FROM TBL_MEMBER
WHERE SID=1;
--> 한 줄 구성 
SELECT SID, NAME, TEL FROM TBL_MEMBER WHERE SID=1
;
--==>> 1	박나현	010-1111-1111

--○ 회원 정보 수정
UPDATE TBL_MEMBER 
SET NAME='박나현', TEL='010-1100-1100' 
WHERE SID=1;
--○ 회원 정보 수정
UPDATE TBL_MEMBER SET NAME='박나현', TEL='010-1100-1100' WHERE SID=1
;

--○ 롤백
ROLLBACK;

--○ 회원 정보 삭제
DELETE 
FROM TBL_MEMBER 
WHERE SID=1;
--> 한 줄 구성
DELETE FROM TBL_MEMBER WHERE SID=1
;

--○ 롤백
ROLLBACK;


--○ 기존 테이블 제거
DROP TABLE TBL_SCORE;
--==>> Table TBL_SCORE이(가) 삭제되었습니다.

--○ 테이블 생성
CREATE TABLE TBL_MEMBERSCORE
( SID   NUMBER
, KOR   NUMBER(3)
, ENG   NUMBER(3)
, MAT   NUMBER(3)
, CONSTRAINT MEMBERSCORE_SID_PK PRIMARY KEY(SID)
, CONSTRAINT MEMBERSCORE_KOR_CK CHECK(KOR BETWEEN 0 AND 100)
, CONSTRAINT MEMBERSCORE_ENG_CK CHECK(ENG BETWEEN 0 AND 100)
, CONSTRAINT MEMBERSCORE_MAT_CK CHECK(MAT BETWEEN 0 AND 100)
, CONSTRAINT MEMBERSCORE_SID_FK FOREIGN KEY(SID)
             REFERENCES TBL_MEMBER(SID)
);
--==>> Table TBL_MEMBERSCORE이(가) 생성되었습니다.

--○ 샘플 데이터 입력
INSERT INTO TBL_MEMBERSCORE(SID, KOR, ENG, MAT) VALUES(1, 20, 30, 40)
;
--==>> 1 행 이(가) 삽입되었습니다.

--○ 확인
SELECT SID, KOR, ENG, MAT
FROM TBL_MEMBERSCORE;
--==>> 1	20	30	40

--○ 커밋
COMMIT;
--==>> 커밋 완료.

















